ALTER TABLE "products"
  ADD COLUMN "productType" TEXT NOT NULL DEFAULT 'TABLET',
  ADD COLUMN "purchaseUnit" TEXT,
  ADD COLUMN "freeStock" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "purchasePrice" DOUBLE PRECISION,
  ADD COLUMN "hsnCode" TEXT,
  ADD COLUMN "gstPercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "unitsPerStrip" INTEGER,
  ADD COLUMN "stripsPerBox" INTEGER,
  ADD COLUMN "rackNumber" TEXT,
  ADD COLUMN "reorderLevel" INTEGER NOT NULL DEFAULT 0;
